backend:
  name: git-gateway
  branch: master

# local_backend: true

media_folder: static/uploads
public_folder: /uploads

collections:
  - name: 'data'
    label: 'Category Data'
    delete: false
    files:
      - label: 'Categories'
        name: 'categories'
        file: 'content/data.json'
        fields:
          - label: Categories
            name: categories
            widget: list
            fields:
              - { label: Title, name: title, widget: string }
              - { label: URL, name: url, widget: string }
              - { label: Image, name: image, widget: image }
              - { label: Body, name: body, widget: text }
              - {
                  label: Links,
                  name: links,
                  widget: list,
                  fields:
                    [
                      { name: title, label: Title, widget: string },
                      { name: url, label: URL, widget: string },
                      {
                        name: target,
                        label: New Window,
                        widget: select,
                        default: _top,
                        options:
                          [
                            { label: Yes, value: _blank },
                            { label: No, value: _top },
                          ],
                      },
                    ],
                }
          - label: Button text
            name: btnText
            widget: string
            default: Find Out More...
